/* eslint-disable import/prefer-default-export */
export const DISABLE_LOADER = 'DISABLE_LOADER';
export const ENABLE_LOADER = 'ACTIVATE_LOADER';
export const SET_USER = 'SET_USER';
export const DELETE_USER = 'DELETE_USER';

export const GET_PROGRESS = 'GET_PROGRESS';

export const GET_HOMELESS = 'GET_HOMELESS';

export const GET_INFO = 'GET_INFO';
export const GENERATE_TRASH = 'GENERATE_TRASH';
export const DELETE_TRASH = 'DELETE_TRASH';
export const GET_TIME_PROGRESS = 'GET_TIME_PROGRESS';

export const CHANGE_FLAG = 'CHANGE_FLAG';

export const CREATE_TRASH_RANDOM = 'CREATE_TRASH_RANDOM';
export const DELETE_TRASH_RANDOM = 'DELETE_TRASH_RANDOM';
export const GET_TIME_HOMELESS = 'GET_TIME_HOMELESS';

export const DELETE_PROGRESS = 'DELETE_PROGRESS';
export const CLEAR_OLD_PROGRESS = 'CLEAR_OLD_PROGRESS';
export const CLEAR_TRASH_RANDOM = 'CLEAR_TRASH_RANDOM';

export const DELETE_TIME_PROGRESS = 'DELETE_TIME_PROGRESS';
export const CLEAR_OLD_TIME_PROGRESS = 'CLEAR_OLD_TIME_PROGRESS';
export const CLEAR_TIME_TRASH_RANDOM = 'CLEAR_TIME_TRASH_RANDOM';

export const SAVE_ONE_NEW_TRASH = 'SAVE_ONE_NEW_TRASH';
export const DELETE_ONE_TRASH = 'DELETE_ONE_TRASH';

export const GET_TABLE_TIME_PROGRESS = 'GET_TABLE_TIME_PROGRESS';

export const CLEAR_TIME_TRASH = 'CLEAR_TIME_TRASH';
export const GENERATE_TIME_TRASH = 'GENERATE_TIME_TRASH';
export const DELETE_TIME_TRASH = 'DELETE_TIME_TRASH';
